### ISSUE TITLE
question for the derivative for initial value

### ISSUE THREAD

**Issue by Fangwq** [cagatayyildiz/npode#1]
Hi, I read the paper and also the code. I am a little confused about the derivative for the  initial value x_0. How to understand this value and the corresponding code?  Thank you very much!

**Comment by cagatayyildiz** [comment]
In our experiments, we fixed x_0 to be the first observation itself. Forward sensitivities could also be computed for x_0. Check `ode_sens` and `ode_kernelsens` [here](https://github.com/cagatayyildiz/npode/blob/master/ode/np_ode_sens.m).
