### ISSUE TITLE
question for the posterior

### ISSUE THREAD

**Issue by Fangwq** [cagatayyildiz/npode#2]
Hi, I read your code and paper carefully. I am a little confused about the posterior calculation, Why do you use `gp.F` in the  file np_ode_fg.m to calculate the posterior ? It seems that you calculate the posterior with non-whitened vector field, but get the corresponding gradient with whitened vector field. When I prune away the `gp.L'` in front of `dF` in function grad_Fw, the result seems wrong. Can you point out my misunderstanding? thank you very much!

**Comment by cagatayyildiz** [comment]
That's just a notation issue. We indeed optimize the Fw variable. While computing the integral, you need F, which is defined as F=L*Fw. You can just replace gp.F with L*gp.Fw, the result would be the same.
